name=Boardoza IRDA Transceiver
version=1.0.0
author=Eray Eroglu <eray.eroglu@boardoza.com>
maintainer=Boardoza <Boardoza.com>
sentence=Library for Boardoza IRDA Transceiver Module
paragraph=This library provides an easy-to-use API for controlling IR (infrared) transceiver modules. It handles 38 kHz carrier frequency generation, modulation and reception of IR signals, customizable packet rates, and burst transmission patterns. Ideal for bidirectional remote control applications, IR communication protocols, and device control systems. With clear example sketches and minimal dependencies, it simplifies IR transmission and reception integration into Arduino and PlatformIO projects.
category=Device Control
url=https://github.com/Boardoza/Boardoza_IRDA_Transceiver_Module
architectures=*
